export { AllDifferentMixin } from './lib/AllDifferent.js';
export type { AllDifferent } from './lib/AllDifferent.js';
export { AllDisjointClassesMixin } from './lib/AllDisjointClasses.js';
export type { AllDisjointClasses } from './lib/AllDisjointClasses.js';
export { AllDisjointPropertiesMixin } from './lib/AllDisjointProperties.js';
export type { AllDisjointProperties } from './lib/AllDisjointProperties.js';
export { AnnotationMixin } from './lib/Annotation.js';
export type { Annotation } from './lib/Annotation.js';
export { AnnotationPropertyMixin } from './lib/AnnotationProperty.js';
export type { AnnotationProperty } from './lib/AnnotationProperty.js';
export { AsymmetricPropertyMixin } from './lib/AsymmetricProperty.js';
export type { AsymmetricProperty } from './lib/AsymmetricProperty.js';
export { AxiomMixin } from './lib/Axiom.js';
export type { Axiom } from './lib/Axiom.js';
export { ClassMixin } from './lib/Class.js';
export type { Class } from './lib/Class.js';
export { DataRangeMixin } from './lib/DataRange.js';
export type { DataRange } from './lib/DataRange.js';
export { DatatypePropertyMixin } from './lib/DatatypeProperty.js';
export type { DatatypeProperty } from './lib/DatatypeProperty.js';
export { DeprecatedClassMixin } from './lib/DeprecatedClass.js';
export type { DeprecatedClass } from './lib/DeprecatedClass.js';
export { DeprecatedPropertyMixin } from './lib/DeprecatedProperty.js';
export type { DeprecatedProperty } from './lib/DeprecatedProperty.js';
export { FunctionalPropertyMixin } from './lib/FunctionalProperty.js';
export type { FunctionalProperty } from './lib/FunctionalProperty.js';
export { InverseFunctionalPropertyMixin } from './lib/InverseFunctionalProperty.js';
export type { InverseFunctionalProperty } from './lib/InverseFunctionalProperty.js';
export { IrreflexivePropertyMixin } from './lib/IrreflexiveProperty.js';
export type { IrreflexiveProperty } from './lib/IrreflexiveProperty.js';
export { NamedIndividualMixin } from './lib/NamedIndividual.js';
export type { NamedIndividual } from './lib/NamedIndividual.js';
export { NegativePropertyAssertionMixin } from './lib/NegativePropertyAssertion.js';
export type { NegativePropertyAssertion } from './lib/NegativePropertyAssertion.js';
export { NothingMixin } from './lib/Nothing.js';
export type { Nothing } from './lib/Nothing.js';
export { ObjectPropertyMixin } from './lib/ObjectProperty.js';
export type { ObjectProperty } from './lib/ObjectProperty.js';
export { OntologyMixin } from './lib/Ontology.js';
export type { Ontology } from './lib/Ontology.js';
export { OntologyPropertyMixin } from './lib/OntologyProperty.js';
export type { OntologyProperty } from './lib/OntologyProperty.js';
export { ReflexivePropertyMixin } from './lib/ReflexiveProperty.js';
export type { ReflexiveProperty } from './lib/ReflexiveProperty.js';
export { RestrictionMixin } from './lib/Restriction.js';
export type { Restriction } from './lib/Restriction.js';
export { SymmetricPropertyMixin } from './lib/SymmetricProperty.js';
export type { SymmetricProperty } from './lib/SymmetricProperty.js';
export { TransitivePropertyMixin } from './lib/TransitiveProperty.js';
export type { TransitiveProperty } from './lib/TransitiveProperty.js';
