export { AllDifferentMixin } from './lib/AllDifferent';
export type { AllDifferent } from './lib/AllDifferent';
export { AllDisjointClassesMixin } from './lib/AllDisjointClasses';
export type { AllDisjointClasses } from './lib/AllDisjointClasses';
export { AllDisjointPropertiesMixin } from './lib/AllDisjointProperties';
export type { AllDisjointProperties } from './lib/AllDisjointProperties';
export { AnnotationMixin } from './lib/Annotation';
export type { Annotation } from './lib/Annotation';
export { AnnotationPropertyMixin } from './lib/AnnotationProperty';
export type { AnnotationProperty } from './lib/AnnotationProperty';
export { AsymmetricPropertyMixin } from './lib/AsymmetricProperty';
export type { AsymmetricProperty } from './lib/AsymmetricProperty';
export { AxiomMixin } from './lib/Axiom';
export type { Axiom } from './lib/Axiom';
export { ClassMixin } from './lib/Class';
export type { Class } from './lib/Class';
export { DataRangeMixin } from './lib/DataRange';
export type { DataRange } from './lib/DataRange';
export { DatatypePropertyMixin } from './lib/DatatypeProperty';
export type { DatatypeProperty } from './lib/DatatypeProperty';
export { DeprecatedClassMixin } from './lib/DeprecatedClass';
export type { DeprecatedClass } from './lib/DeprecatedClass';
export { DeprecatedPropertyMixin } from './lib/DeprecatedProperty';
export type { DeprecatedProperty } from './lib/DeprecatedProperty';
export { FunctionalPropertyMixin } from './lib/FunctionalProperty';
export type { FunctionalProperty } from './lib/FunctionalProperty';
export { InverseFunctionalPropertyMixin } from './lib/InverseFunctionalProperty';
export type { InverseFunctionalProperty } from './lib/InverseFunctionalProperty';
export { IrreflexivePropertyMixin } from './lib/IrreflexiveProperty';
export type { IrreflexiveProperty } from './lib/IrreflexiveProperty';
export { NamedIndividualMixin } from './lib/NamedIndividual';
export type { NamedIndividual } from './lib/NamedIndividual';
export { NegativePropertyAssertionMixin } from './lib/NegativePropertyAssertion';
export type { NegativePropertyAssertion } from './lib/NegativePropertyAssertion';
export { NothingMixin } from './lib/Nothing';
export type { Nothing } from './lib/Nothing';
export { ObjectPropertyMixin } from './lib/ObjectProperty';
export type { ObjectProperty } from './lib/ObjectProperty';
export { OntologyMixin } from './lib/Ontology';
export type { Ontology } from './lib/Ontology';
export { OntologyPropertyMixin } from './lib/OntologyProperty';
export type { OntologyProperty } from './lib/OntologyProperty';
export { ReflexivePropertyMixin } from './lib/ReflexiveProperty';
export type { ReflexiveProperty } from './lib/ReflexiveProperty';
export { RestrictionMixin } from './lib/Restriction';
export type { Restriction } from './lib/Restriction';
export { SymmetricPropertyMixin } from './lib/SymmetricProperty';
export type { SymmetricProperty } from './lib/SymmetricProperty';
export { TransitivePropertyMixin } from './lib/TransitiveProperty';
export type { TransitiveProperty } from './lib/TransitiveProperty';
