export type { IriTemplateEx } from './IriTemplateEx.js'
export { IriTemplateExMixin } from './IriTemplateEx.js'
export type { MemberAssertion } from './MemberAssertion.js'
export { MemberAssertionMixin } from './MemberAssertion.js'
export { VariableRepresentationExMixin } from './VariableRepresentation.js'
