export { namespace } from './lib/decorators/namespace'
export { default as ResourceFactoryImpl, ResourceFactory, Constructor, ResourceIndexer } from './lib/ResourceFactory'
export { default as RdfResourceImpl, RdfResource, ResourceIdentifier, init } from './lib/RdfResource'
export { property } from './lib/decorators/property'
export { crossBoundaries } from './lib/path'
export { default as TypeCollectionImpl, TypeCollection } from './lib/TypeCollection'
