export { AccumulationRelationMixin } from './lib/AccumulationRelation.js';
export type { AccumulationRelation } from './lib/AccumulationRelation.js';
export { ActivityMixin } from './lib/Activity.js';
export type { Activity } from './lib/Activity.js';
export { ActivityDocumentationRelationMixin } from './lib/ActivityDocumentationRelation.js';
export type { ActivityDocumentationRelation } from './lib/ActivityDocumentationRelation.js';
export { ActivityTypeMixin } from './lib/ActivityType.js';
export type { ActivityType } from './lib/ActivityType.js';
export { AgentMixin } from './lib/Agent.js';
export type { Agent } from './lib/Agent.js';
export { AgentControlRelationMixin } from './lib/AgentControlRelation.js';
export type { AgentControlRelation } from './lib/AgentControlRelation.js';
export { AgentHierarchicalRelationMixin } from './lib/AgentHierarchicalRelation.js';
export type { AgentHierarchicalRelation } from './lib/AgentHierarchicalRelation.js';
export { AgentNameMixin } from './lib/AgentName.js';
export type { AgentName } from './lib/AgentName.js';
export { AgentTemporalRelationMixin } from './lib/AgentTemporalRelation.js';
export type { AgentTemporalRelation } from './lib/AgentTemporalRelation.js';
export { AgentToAgentRelationMixin } from './lib/AgentToAgentRelation.js';
export type { AgentToAgentRelation } from './lib/AgentToAgentRelation.js';
export { AppellationMixin } from './lib/Appellation.js';
export type { Appellation } from './lib/Appellation.js';
export { AppellationRelationMixin } from './lib/AppellationRelation.js';
export type { AppellationRelation } from './lib/AppellationRelation.js';
export { AuthorityRelationMixin } from './lib/AuthorityRelation.js';
export type { AuthorityRelation } from './lib/AuthorityRelation.js';
export { AuthorshipRelationMixin } from './lib/AuthorshipRelation.js';
export type { AuthorshipRelation } from './lib/AuthorshipRelation.js';
export { CarrierExtentMixin } from './lib/CarrierExtent.js';
export type { CarrierExtent } from './lib/CarrierExtent.js';
export { CarrierTypeMixin } from './lib/CarrierType.js';
export type { CarrierType } from './lib/CarrierType.js';
export { ChildRelationMixin } from './lib/ChildRelation.js';
export type { ChildRelation } from './lib/ChildRelation.js';
export { ConceptMixin } from './lib/Concept.js';
export type { Concept } from './lib/Concept.js';
export { ContentTypeMixin } from './lib/ContentType.js';
export type { ContentType } from './lib/ContentType.js';
export { CoordinatesMixin } from './lib/Coordinates.js';
export type { Coordinates } from './lib/Coordinates.js';
export { CorporateBodyMixin } from './lib/CorporateBody.js';
export type { CorporateBody } from './lib/CorporateBody.js';
export { CorporateBodyTypeMixin } from './lib/CorporateBodyType.js';
export type { CorporateBodyType } from './lib/CorporateBodyType.js';
export { CorrespondenceRelationMixin } from './lib/CorrespondenceRelation.js';
export type { CorrespondenceRelation } from './lib/CorrespondenceRelation.js';
export { CreationRelationMixin } from './lib/CreationRelation.js';
export type { CreationRelation } from './lib/CreationRelation.js';
export { DateMixin } from './lib/Date.js';
export type { Date } from './lib/Date.js';
export { DateTypeMixin } from './lib/DateType.js';
export type { DateType } from './lib/DateType.js';
export { DemographicGroupMixin } from './lib/DemographicGroup.js';
export type { DemographicGroup } from './lib/DemographicGroup.js';
export { DerivationRelationMixin } from './lib/DerivationRelation.js';
export type { DerivationRelation } from './lib/DerivationRelation.js';
export { DescendanceRelationMixin } from './lib/DescendanceRelation.js';
export type { DescendanceRelation } from './lib/DescendanceRelation.js';
export { DocumentaryFormTypeMixin } from './lib/DocumentaryFormType.js';
export type { DocumentaryFormType } from './lib/DocumentaryFormType.js';
export { EventMixin } from './lib/Event.js';
export type { Event } from './lib/Event.js';
export { EventRelationMixin } from './lib/EventRelation.js';
export type { EventRelation } from './lib/EventRelation.js';
export { EventTypeMixin } from './lib/EventType.js';
export type { EventType } from './lib/EventType.js';
export { ExtentMixin } from './lib/Extent.js';
export type { Extent } from './lib/Extent.js';
export { ExtentTypeMixin } from './lib/ExtentType.js';
export type { ExtentType } from './lib/ExtentType.js';
export { FamilyMixin } from './lib/Family.js';
export type { Family } from './lib/Family.js';
export { FamilyRelationMixin } from './lib/FamilyRelation.js';
export type { FamilyRelation } from './lib/FamilyRelation.js';
export { FamilyTypeMixin } from './lib/FamilyType.js';
export type { FamilyType } from './lib/FamilyType.js';
export { FunctionalEquivalenceRelationMixin } from './lib/FunctionalEquivalenceRelation.js';
export type { FunctionalEquivalenceRelation } from './lib/FunctionalEquivalenceRelation.js';
export { GroupMixin } from './lib/Group.js';
export type { Group } from './lib/Group.js';
export { GroupSubdivisionRelationMixin } from './lib/GroupSubdivisionRelation.js';
export type { GroupSubdivisionRelation } from './lib/GroupSubdivisionRelation.js';
export { IdentifierMixin } from './lib/Identifier.js';
export type { Identifier } from './lib/Identifier.js';
export { IdentifierTypeMixin } from './lib/IdentifierType.js';
export type { IdentifierType } from './lib/IdentifierType.js';
export { InstantiationMixin } from './lib/Instantiation.js';
export type { Instantiation } from './lib/Instantiation.js';
export { InstantiationExtentMixin } from './lib/InstantiationExtent.js';
export type { InstantiationExtent } from './lib/InstantiationExtent.js';
export { InstantiationToInstantiationRelationMixin } from './lib/InstantiationToInstantiationRelation.js';
export type { InstantiationToInstantiationRelation } from './lib/InstantiationToInstantiationRelation.js';
export { IntellectualPropertyRightsRelationMixin } from './lib/IntellectualPropertyRightsRelation.js';
export type { IntellectualPropertyRightsRelation } from './lib/IntellectualPropertyRightsRelation.js';
export { KnowingOfRelationMixin } from './lib/KnowingOfRelation.js';
export type { KnowingOfRelation } from './lib/KnowingOfRelation.js';
export { KnowingRelationMixin } from './lib/KnowingRelation.js';
export type { KnowingRelation } from './lib/KnowingRelation.js';
export { LanguageMixin } from './lib/Language.js';
export type { Language } from './lib/Language.js';
export { LeadershipRelationMixin } from './lib/LeadershipRelation.js';
export type { LeadershipRelation } from './lib/LeadershipRelation.js';
export { LegalStatusMixin } from './lib/LegalStatus.js';
export type { LegalStatus } from './lib/LegalStatus.js';
export { ManagementRelationMixin } from './lib/ManagementRelation.js';
export type { ManagementRelation } from './lib/ManagementRelation.js';
export { MandateMixin } from './lib/Mandate.js';
export type { Mandate } from './lib/Mandate.js';
export { MandateRelationMixin } from './lib/MandateRelation.js';
export type { MandateRelation } from './lib/MandateRelation.js';
export { MandateTypeMixin } from './lib/MandateType.js';
export type { MandateType } from './lib/MandateType.js';
export { MechanismMixin } from './lib/Mechanism.js';
export type { Mechanism } from './lib/Mechanism.js';
export { MembershipRelationMixin } from './lib/MembershipRelation.js';
export type { MembershipRelation } from './lib/MembershipRelation.js';
export { MigrationRelationMixin } from './lib/MigrationRelation.js';
export type { MigrationRelation } from './lib/MigrationRelation.js';
export { NameMixin } from './lib/Name.js';
export type { Name } from './lib/Name.js';
export { OccupationTypeMixin } from './lib/OccupationType.js';
export type { OccupationType } from './lib/OccupationType.js';
export { OrganicOrFunctionalProvenanceRelationMixin } from './lib/OrganicOrFunctionalProvenanceRelation.js';
export type { OrganicOrFunctionalProvenanceRelation } from './lib/OrganicOrFunctionalProvenanceRelation.js';
export { OrganicProvenanceRelationMixin } from './lib/OrganicProvenanceRelation.js';
export type { OrganicProvenanceRelation } from './lib/OrganicProvenanceRelation.js';
export { OwnershipRelationMixin } from './lib/OwnershipRelation.js';
export type { OwnershipRelation } from './lib/OwnershipRelation.js';
export { PerformanceRelationMixin } from './lib/PerformanceRelation.js';
export type { PerformanceRelation } from './lib/PerformanceRelation.js';
export { PersonMixin } from './lib/Person.js';
export type { Person } from './lib/Person.js';
export { PhysicalLocationMixin } from './lib/PhysicalLocation.js';
export type { PhysicalLocation } from './lib/PhysicalLocation.js';
export { PlaceMixin } from './lib/Place.js';
export type { Place } from './lib/Place.js';
export { PlaceNameMixin } from './lib/PlaceName.js';
export type { PlaceName } from './lib/PlaceName.js';
export { PlaceRelationMixin } from './lib/PlaceRelation.js';
export type { PlaceRelation } from './lib/PlaceRelation.js';
export { PlaceTypeMixin } from './lib/PlaceType.js';
export type { PlaceType } from './lib/PlaceType.js';
export { PositionMixin } from './lib/Position.js';
export type { Position } from './lib/Position.js';
export { PositionHoldingRelationMixin } from './lib/PositionHoldingRelation.js';
export type { PositionHoldingRelation } from './lib/PositionHoldingRelation.js';
export { PositionToGroupRelationMixin } from './lib/PositionToGroupRelation.js';
export type { PositionToGroupRelation } from './lib/PositionToGroupRelation.js';
export { ProductionTechniqueTypeMixin } from './lib/ProductionTechniqueType.js';
export type { ProductionTechniqueType } from './lib/ProductionTechniqueType.js';
export { ProxyMixin } from './lib/Proxy.js';
export type { Proxy } from './lib/Proxy.js';
export { RecordMixin } from './lib/Record.js';
export type { Record } from './lib/Record.js';
export { RecordPartMixin } from './lib/RecordPart.js';
export type { RecordPart } from './lib/RecordPart.js';
export { RecordResourceMixin } from './lib/RecordResource.js';
export type { RecordResource } from './lib/RecordResource.js';
export { RecordResourceExtentMixin } from './lib/RecordResourceExtent.js';
export type { RecordResourceExtent } from './lib/RecordResourceExtent.js';
export { RecordResourceGeneticRelationMixin } from './lib/RecordResourceGeneticRelation.js';
export type { RecordResourceGeneticRelation } from './lib/RecordResourceGeneticRelation.js';
export { RecordResourceHoldingRelationMixin } from './lib/RecordResourceHoldingRelation.js';
export type { RecordResourceHoldingRelation } from './lib/RecordResourceHoldingRelation.js';
export { RecordResourceToInstantiationRelationMixin } from './lib/RecordResourceToInstantiationRelation.js';
export type { RecordResourceToInstantiationRelation } from './lib/RecordResourceToInstantiationRelation.js';
export { RecordResourceToRecordResourceRelationMixin } from './lib/RecordResourceToRecordResourceRelation.js';
export type { RecordResourceToRecordResourceRelation } from './lib/RecordResourceToRecordResourceRelation.js';
export { RecordSetMixin } from './lib/RecordSet.js';
export type { RecordSet } from './lib/RecordSet.js';
export { RecordSetTypeMixin } from './lib/RecordSetType.js';
export type { RecordSetType } from './lib/RecordSetType.js';
export { RecordStateMixin } from './lib/RecordState.js';
export type { RecordState } from './lib/RecordState.js';
export { RelationMixin } from './lib/Relation.js';
export type { Relation } from './lib/Relation.js';
export { RepresentationTypeMixin } from './lib/RepresentationType.js';
export type { RepresentationType } from './lib/RepresentationType.js';
export { RoleTypeMixin } from './lib/RoleType.js';
export type { RoleType } from './lib/RoleType.js';
export { RuleMixin } from './lib/Rule.js';
export type { Rule } from './lib/Rule.js';
export { RuleRelationMixin } from './lib/RuleRelation.js';
export type { RuleRelation } from './lib/RuleRelation.js';
export { RuleTypeMixin } from './lib/RuleType.js';
export type { RuleType } from './lib/RuleType.js';
export { SequentialRelationMixin } from './lib/SequentialRelation.js';
export type { SequentialRelation } from './lib/SequentialRelation.js';
export { SiblingRelationMixin } from './lib/SiblingRelation.js';
export type { SiblingRelation } from './lib/SiblingRelation.js';
export { SpouseRelationMixin } from './lib/SpouseRelation.js';
export type { SpouseRelation } from './lib/SpouseRelation.js';
export { TeachingRelationMixin } from './lib/TeachingRelation.js';
export type { TeachingRelation } from './lib/TeachingRelation.js';
export { TemporalRelationMixin } from './lib/TemporalRelation.js';
export type { TemporalRelation } from './lib/TemporalRelation.js';
export { ThingMixin } from './lib/Thing.js';
export type { Thing } from './lib/Thing.js';
export { TitleMixin } from './lib/Title.js';
export type { Title } from './lib/Title.js';
export { TypeMixin } from './lib/Type.js';
export type { Type } from './lib/Type.js';
export { TypeRelationMixin } from './lib/TypeRelation.js';
export type { TypeRelation } from './lib/TypeRelation.js';
export { UnitOfMeasurementMixin } from './lib/UnitOfMeasurement.js';
export type { UnitOfMeasurement } from './lib/UnitOfMeasurement.js';
export { WholePartRelationMixin } from './lib/WholePartRelation.js';
export type { WholePartRelation } from './lib/WholePartRelation.js';
export { WorkRelationMixin } from './lib/WorkRelation.js';
export type { WorkRelation } from './lib/WorkRelation.js';
