export { namespace } from './lib/decorators/namespace'
export { ResourceFactory, Constructor, ResourceIndexer } from './lib/ResourceFactory'
export { RdfResource, ResourceIdentifier } from './lib/RdfResource'
export { property } from './lib/decorators/property'
export { crossBoundaries } from './lib/path'
